### ISSUE TITLE
Hostnames don't contain roles

### ISSUE THREAD

**Issue by net-id** [Bridgewater/appetite#6]
Hi,
Our environment has existing hostnames that do not contain the server class, site or index.
What solution do you recommend for overcoming this? 

Thanks                 ...Laurie:{)

**Comment by kalpatel01** [comment]
I would take a look at [param hosts](https://github.com/Bridgewater/appetite/blob/master/docs/configurations.md#param_hosts) in the documentation.

Appetite does not use hostnames from the box, only DNS (If it exists) for name resolution.  You can pair IP addresses to a appetite hostname (class, index, site) you want.

The only "got ya" is the appetite host name is also passed into templating so if you have base configs and your layering hostname, these would not match the existing hostname.
